[package]
name = "petrivet"
version = "0.1.0"
edition = "2024"
description = "A Rust library for working with Petri nets"
repository = "https://github.com/MichaelOwenDyer/petrivet"
keywords = ["petrinets", "modeling", "analysis"]

[dependencies]
ahash = "0.8.12"
good_lp = { version = "1.15.1", default-features = false, features = ["microlp"] }
petgraph = "0.8.3"
graph-cycles = "0.3.0"
quick-xml = { version = "0.40.1", features = ["serialize"], optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
tap = "1.0.1"
oxiz = "0.2.3"

[features]
default = ["pnml"]
pnml = ["serde", "quick-xml"]

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "analysis"
harness = false
