use crate::class::NetClass;
use crate::core::analysis::semi_decision;
use crate::core::state_space::ExploreNext;
use crate::marking::Marking;
use crate::net::{Net, Transition};
use crate::prelude::PetriNet;
use crate::state_space::ExplorationOrder;
use ahash::HashMap;

/// Result of reachability analysis.
///
/// Three possible outcomes:
/// - `Reachable`: the target is definitely reachable, with a witness.
/// - `Unreachable`: the target is definitely unreachable, with a proof.
/// - `Inconclusive`: current algorithms could not decide (e.g., unbounded
///   general net where LP/ILP filters pass but full exploration is infinite).
#[derive(Debug, Clone)]
pub enum ReachabilityResult {
    /// The target marking is reachable from M₀.
    Reachable(ReachabilityProof),
    /// The target marking is definitely not reachable from M₀.
    Unreachable(UnreachabilityProof),
    /// Current algorithms could not decide.
    Inconclusive,
}

impl ReachabilityResult {
    /// Whether the target is definitely reachable.
    #[must_use]
    pub const fn is_reachable(&self) -> bool {
        matches!(self, Self::Reachable(_))
    }

    /// Whether the target is definitely unreachable.
    #[must_use]
    pub const fn is_unreachable(&self) -> bool {
        matches!(self, Self::Unreachable(_))
    }
}

#[derive(Debug, Clone)]
pub enum ReachabilityProof {
    /// Valid for S-Systems (State Machines) that are strongly connected and M0(S) > 0.
    /// Proof relies on strict token conservation (Theorem 5.1.5).
    LiveStateMachineTokenConservation { marking_sum: u32 },

    /// Valid for T-Systems (Marked Graphs) that are live (all circuits marked).
    /// Proof relies on a non-negative integer solution to the marking equation (Theorem 5.2.7).
    LiveMarkedGraphMarkingEquationIntegerSolution(HashMap<Transition, u32>),

    /// Valid for Free-Choice systems that are live and bounded.
    /// Proof relies on an integer solution to the marking equation PLUS
    /// a proof that the subnet generated by the fired transitions has no unmarked traps (Theorem 5.3.18).
    LiveBoundedFreeChoiceMarkingEquationWithTrapCheck(HashMap<Transition, u32>),

    /// The universal fallback for non-live subclasses or general unrestricted nets.
    FiringSequence(Box<[Transition]>),
}

/// Proof that a marking is unreachable.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum UnreachabilityProof {
    /// The net is an S-net (state machine): every transition preserves token count,
    /// so any marking with a different token sum than M₀ is unreachable.
    /// Requires no liveness or connectivity conditions.
    StateMachineTokenConservation,
    /// The LP marking equation (rational relaxation) is infeasible.
    /// Some S-invariant is violated.
    MarkingEquationNoRationalSolution,
    /// The ILP marking equation (integer) is infeasible.
    /// Stronger than LP: no integer firing count vector exists.
    MarkingEquationNoIntegerSolution,
    /// Full state space explored; target not found.
    ExhaustiveSearch,
}

impl From<ReachabilityProof> for ReachabilityResult {
    fn from(value: ReachabilityProof) -> Self {
        ReachabilityResult::Reachable(value)
    }
}

impl From<UnreachabilityProof> for ReachabilityResult {
    fn from(value: UnreachabilityProof) -> Self {
        ReachabilityResult::Unreachable(value)
    }
}

impl<N: AsRef<Net>> PetriNet<N> {
    /// If there is an efficient (polynomial-time) procedure to determine
    /// whether the given target marking is reachable in this Petri net,
    /// returns Some(_) with the answer.
    /// Returns None if the answer would not be efficient to compute.
    #[must_use]
    pub fn is_efficiently_reachable(&self, target: &Marking<u32>) -> Option<bool> {
        // todo: efficient check necessary for reachability: maximal unmarked trap in target must be unmarked in M0
        match self.class() {
            NetClass::Circuit => Some(self.marking.sum() == target.total_tokens()),
            NetClass::StateMachine if self.is_live() => {
                Some(self.marking.sum() == target.total_tokens())
            }
            // NetClass::MarkedGraph if self.is_live() => Some(self.marking() ~ target) // todo: ~ relation
            // NetClass::FreeChoice if self.is_live() && self.is_bounded() => None, // todo: requires ILP + trap check
            _ => None,
        }
    }

    /// Whether `target` is reachable from the initial marking.
    ///
    /// Delegates to [`analyze_reachability`](Self::analyze_reachability).
    /// Returns `false` for inconclusive results.
    #[must_use]
    pub fn is_reachable(&self, target: &Marking<u32>) -> bool {
        self.is_efficiently_reachable(target)
            .unwrap_or_else(|| self.analyze_reachability(target).is_reachable())
    }

    /// Analyzes reachability of a target marking with structured evidence.
    ///
    /// Returns [`ReachabilityResult::Reachable`] with a firing sequence,
    /// [`ReachabilityResult::Unreachable`] with a proof, or
    /// [`ReachabilityResult::Inconclusive`] if current algorithms cannot decide.
    ///
    /// Strategy (ascending cost):
    /// 1. **S-nets**: token conservation (exact, polynomial).
    /// 2. **T-nets**: ILP marking equation (exact).
    /// 3. **General**: LP filter → ILP filter → state space exploration.
    ///
    /// For unbounded general nets where LP/ILP filters pass, returns
    /// `Inconclusive` rather than attempting infinite exploration.
    #[must_use]
    pub fn analyze_reachability(&self, target: &Marking<u32>) -> ReachabilityResult {
        let target = self.mapping.decode(target.clone());

        if self.marking == target {
            return ReachabilityProof::FiringSequence(Box::new([])).into();
        }

        // Token conservation: for any S-net every transition has |•t| = |t•| = 1,
        // so M₀(S) = M(S) for all reachable M. A different token sum proves unreachability
        // without requiring strong connectivity or liveness.
        if self.class().is_state_machine() {
            let initial_sum = self.marking.iter().sum::<u32>();
            let target_sum = target.iter().sum::<u32>();
            if initial_sum != target_sum {
                return UnreachabilityProof::StateMachineTokenConservation.into();
            }
            // Equal token sum in a live (strongly connected + marked) S-net: any marking
            // with the same sum is reachable (Theorem 5.1.5).
            if self.is_strongly_connected() {
                return ReachabilityProof::LiveStateMachineTokenConservation {
                    marking_sum: initial_sum,
                }
                .into();
            }
        }

        if self.class().is_marked_graph() && self.is_live() {
            return semi_decision::find_marking_equation_integer_solution(
                &self.dense_net,
                &self.marking,
                &target,
            )
            .map_or_else(
                || UnreachabilityProof::MarkingEquationNoIntegerSolution.into(),
                |solution| {
                    let solution = self.transitions().zip(solution).collect();
                    ReachabilityProof::LiveMarkedGraphMarkingEquationIntegerSolution(solution)
                        .into()
                },
            );
        }

        if semi_decision::find_marking_equation_rational_solution(
            &self.dense_net,
            &self.marking,
            &target,
        )
        .is_none()
        {
            return UnreachabilityProof::MarkingEquationNoRationalSolution.into();
        }

        // todo: only test ILP if the rational solution is already an integer solution
        if semi_decision::find_marking_equation_integer_solution(
            &self.dense_net,
            &self.marking,
            &target,
        )
        .is_none()
        {
            return UnreachabilityProof::MarkingEquationNoIntegerSolution.into();
        }

        let mut explorer = self
            .explore_coverability(ExplorationOrder::BreadthFirst)
            .core;
        while let Some((_t_idx, node_idx, is_new)) = explorer.explore_next() {
            if !is_new {
                continue;
            }
            let marking = explorer.state_space.marking_at(node_idx);
            if marking.has_omega() {
                return ReachabilityResult::Inconclusive;
            }
            if marking == target {
                let path = explorer
                    .path_from_initial_to(marking)
                    .expect("marking is in graph")
                    .into_iter()
                    .map(|t_idx| self.mapping.transition(t_idx))
                    .collect();
                return ReachabilityProof::FiringSequence(path).into();
            }
        }
        UnreachabilityProof::ExhaustiveSearch.into()
    }
}

#[cfg(test)]
mod tests {
    use crate::builder::NetBuilder;
    use crate::class::NetClass;

    #[test]
    fn s_net_reachability_dispatches() {
        let (net, p0, _t0, p1, _t1) = crate::api::system::tests::two_place_cycle();
        let sys = net.with_initial_marking([(p0, 1)]);
        assert!(sys.is_reachable(&[(p1, 1)].into()));
        assert!(sys.is_reachable(&[(p0, 1)].into()));
        assert!(!sys.is_reachable(&[(p0, 2)].into()));
        assert!(!sys.is_reachable(&[].into()));
    }

    #[test]
    fn t_net_reachability_dispatches() {
        let mut b = NetBuilder::new();
        let [p0, p1, p2] = b.add_places();
        let [t0, t1] = b.add_transitions();
        b.add_arc((p0, t0));
        b.add_arc((p1, t0));
        b.add_arcs((t0, p2, t1));
        b.add_arc((t1, p0));
        b.add_arc((t1, p1));
        let net = b.build().unwrap();
        assert_eq!(net.class(), NetClass::MarkedGraph);
        let sys = net.with_initial_marking([(p0, 1), (p1, 1)]);
        assert!(sys.is_reachable(&[(p2, 1)].into()));
        assert!(sys.is_reachable(&[(p0, 1), (p1, 1)].into()));
        assert!(!sys.is_reachable(&[(p1, 1)].into()));
    }

    #[test]
    fn general_net_reachability_fallback() {
        let mut b = NetBuilder::new();
        let [p0, p1, p2] = b.add_places();
        let [t0, t1, t2] = b.add_transitions();
        b.add_arcs((p0, t0, p1));
        b.add_arcs((p0, t1, p2));
        b.add_arcs((p1, t2, p0));
        b.add_arcs((p2, t2, p0));
        b.add_arc((p1, t1)); // extra arc to make it a general net
        let net = b.build().unwrap();
        assert_eq!(net.class(), NetClass::General);
        let sys = net.with_initial_marking([(p0, 1)]);
        assert!(sys.is_reachable(&[(p0, 1)].into()));
        assert!(sys.is_reachable(&[(p1, 1)].into()));
    }
}
