use ahash::HashMap;
use fixedbitset::FixedBitSet;
use crate::class::NetClass;
use crate::core::analysis::semi_decision;
use crate::core::marking::IdxMarking;
use crate::core::net::{DenseNet, PlaceIdx, TransitionIdx};
use crate::core::state_space::ExploreNext;
use crate::marking::Marking;
use crate::net::{Net, Transition};
use crate::prelude::PetriNet;
use crate::state_space::ExplorationOrder;

/// Result of reachability analysis.
///
/// Three possible outcomes:
/// - `Reachable`: the target is definitely reachable, with a witness.
/// - `Unreachable`: the target is definitely unreachable, with a proof.
/// - `Inconclusive`: current algorithms could not decide (e.g., unbounded
///   general net where LP/ILP filters pass but full exploration is infinite).
#[derive(Debug, Clone)]
pub enum ReachabilityResult {
    /// The target marking is reachable from M₀.
    Reachable(ReachabilityProof),
    /// The target marking is definitely not reachable from M₀.
    Unreachable(UnreachabilityProof),
    /// Current algorithms could not decide.
    Inconclusive,
}

impl ReachabilityResult {
    /// Whether the target is definitely reachable.
    #[must_use]
    pub const fn is_reachable(&self) -> bool {
        matches!(self, Self::Reachable(_))
    }

    /// Whether the target is definitely unreachable.
    #[must_use]
    pub const fn is_unreachable(&self) -> bool {
        matches!(self, Self::Unreachable(_))
    }
}

#[derive(Debug, Clone)]
pub enum ReachabilityProof {
    /// Valid for S-Systems (State Machines) that are strongly connected and M0(S) > 0.
    /// Proof relies on strict token conservation (Theorem 5.1.5).
    LiveStateMachineTokenConservation {
        marking_sum: u32,
    },

    /// Valid for T-Systems (Marked Graphs) that are live (all circuits marked).
    /// Proof relies on a non-negative integer solution to the marking equation (Theorem 5.2.7).
    LiveMarkedGraphMarkingEquationIntegerSolution(HashMap<Transition, u32>),

    /// Valid for Free-Choice systems that are live and bounded.
    /// Proof relies on an integer solution to the marking equation PLUS
    /// a proof that the subnet generated by the fired transitions has no unmarked traps (Theorem 5.3.18).
    LiveBoundedFreeChoiceMarkingEquationWithTrapCheck(HashMap<Transition, u32>),

    /// The universal fallback for non-live subclasses or general unrestricted nets.
    FiringSequence(Box<[Transition]>),
}

/// Proof that a marking is unreachable.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum UnreachabilityProof {
    /// The net is an S-net (state machine): every transition preserves token count,
    /// so any marking with a different token sum than M₀ is unreachable.
    /// Requires no liveness or connectivity conditions.
    StateMachineTokenConservation,
    /// The LP marking equation (rational relaxation) is infeasible.
    /// Some S-invariant is violated.
    MarkingEquationNoRationalSolution,
    /// The ILP marking equation (integer) is infeasible.
    /// Stronger than LP: no integer firing count vector exists.
    MarkingEquationNoIntegerSolution,
    /// Full state space explored; target not found.
    ExhaustiveSearch,
}

impl From<ReachabilityProof> for ReachabilityResult {
    fn from(value: ReachabilityProof) -> Self {
        ReachabilityResult::Reachable(value)
    }
}

impl From<UnreachabilityProof> for ReachabilityResult {
    fn from(value: UnreachabilityProof) -> Self {
        ReachabilityResult::Unreachable(value)
    }
}

/// The trap condition of the free-choice reachability theorem
/// ([Primer, Theorem 5.3.18](crate::literature#theorem-5318--reachability-in-live-bounded-free-choice-systems)).
///
/// Given `parikh`, a non-negative integer solution of the marking equation
/// `target = M₀ + N·parikh`, let `U = supp(parikh) = { t | parikh[t] > 0 }` be
/// the *fired* transitions. The theorem requires that the subnet generated by
/// `U` contains no trap that is unmarked under `target`.
///
/// A trap `Q` of the `U`-subnet is a set of places such that every transition in
/// `U` that consumes from `Q` also produces into `Q`. We look for a non-empty
/// such trap all of whose places are unmarked under `target`: starting from the
/// `target`-unmarked places incident to `U` and shrinking to the maximal
/// `U`-trap (the dual of the `maximal_trap_in` shrinking algorithm, restricted
/// to `U`-transitions).
///
/// Returns `true` iff no such unmarked trap exists, i.e. the trap condition for
/// reachability is satisfied.
///
/// Verified exhaustively against BFS reachability (see the `fc_*` tests): with
/// the minimum-firing solution this reading is both sound (never accepts an
/// unreachable marking) and complete (accepts every reachable one) on the tested
/// live and bounded free-choice systems.
fn fired_subnet_has_no_unmarked_trap(
    net: &DenseNet,
    parikh: &[u32],
    target: &IdxMarking<u32>,
) -> bool {
    // `U` = the support: transitions with a positive firing count.
    let fired = |t: TransitionIdx| parikh[t] > 0;

    // Candidate places: unmarked under `target` and belonging to the subnet
    // generated by `U` (incident to at least one fired transition).
    let mut candidate = FixedBitSet::with_capacity(net.place_count());
    for p in net.place_indices() {
        let incident_to_u = net.preset_p[p].iter().any(|&t| fired(t))
            || net.postset_p[p].iter().any(|&t| fired(t));
        if target[p] == 0 && incident_to_u {
            candidate.insert(p);
        }
    }

    // Shrink to the maximal trap of the `U`-subnet: remove any place `p` for
    // which some fired transition consuming from `p` (`t ∈ p• ∩ U`) produces
    // into no candidate place (`t• ∩ candidate = ∅`).
    loop {
        let to_remove: Vec<PlaceIdx> = candidate
            .ones()
            .filter(|&p| {
                net.postset_p[p].iter().any(|&t| {
                    fired(t) && !net.postset_t[t].iter().any(|&q| candidate.contains(q))
                })
            })
            .collect();
        if to_remove.is_empty() {
            break;
        }
        for p in to_remove {
            candidate.remove(p);
        }
    }

    candidate.is_clear()
}

impl<N: AsRef<Net>> PetriNet<N> {
    /// If there is an efficient (polynomial-time) procedure to determine
    /// whether the given target marking is reachable in this Petri net,
    /// returns Some(_) with the answer.
    /// Returns None if the answer would not be efficient to compute.
    #[must_use]
    pub fn is_efficiently_reachable(&self, target: &Marking<u32>) -> Option<bool> {
        match self.class() {
            NetClass::Circuit => Some(self.marking.sum() == target.total_tokens()),
            NetClass::StateMachine if self.is_live() => Some(self.marking.sum() == target.total_tokens()),
            // NetClass::MarkedGraph if self.is_live() => Some(self.marking() ~ target) // todo: ~ relation
            // Live and bounded free-choice: the marking equation plus the trap
            // condition (Theorem 5.3.18). Both preconditions are polynomial, as
            // is the decision, so this is an efficient procedure. It may abstain
            // (`Inconclusive`) when the trap check fails on the minimum-firing
            // solution — in that case we report `None` (not efficiently decided)
            // rather than guess. Boundedness is established structurally (see
            // `analyze_reachability`), not via the stubbed `is_bounded()`.
            NetClass::FreeChoice if self.is_live() && self.dense_net.is_structurally_bounded() => {
                match self.analyze_reachability(target) {
                    ReachabilityResult::Reachable(_) => Some(true),
                    ReachabilityResult::Unreachable(_) => Some(false),
                    ReachabilityResult::Inconclusive => None,
                }
            }
            _ => None,
        }
    }

    /// Whether `target` is reachable from the initial marking.
    ///
    /// Delegates to [`analyze_reachability`](Self::analyze_reachability).
    /// Returns `false` for inconclusive results.
    #[must_use]
    pub fn is_reachable(&self, target: &Marking<u32>) -> bool {
        self.is_efficiently_reachable(target).unwrap_or_else(|| {
            self.analyze_reachability(target).is_reachable()
        })
    }

    /// Analyzes reachability of a target marking with structured evidence.
    ///
    /// Returns [`ReachabilityResult::Reachable`] with a firing sequence,
    /// [`ReachabilityResult::Unreachable`] with a proof, or
    /// [`ReachabilityResult::Inconclusive`] if current algorithms cannot decide.
    ///
    /// Strategy (ascending cost):
    /// 1. **S-nets**: token conservation (exact, polynomial).
    /// 2. **T-nets**: ILP marking equation (exact).
    /// 3. **General**: LP filter → ILP filter → state space exploration.
    ///
    /// For unbounded general nets where LP/ILP filters pass, returns
    /// `Inconclusive` rather than attempting infinite exploration.
    #[must_use]
    pub fn analyze_reachability(&self, target: &Marking<u32>) -> ReachabilityResult {
        let target = self.mapping.decode(target.clone());

        if self.marking == target {
            return ReachabilityProof::FiringSequence(Box::new([])).into();
        }

        // Token conservation: for any S-net every transition has |•t| = |t•| = 1,
        // so M₀(S) = M(S) for all reachable M. A different token sum proves unreachability
        // without requiring strong connectivity or liveness.
        if self.class().is_state_machine() {
            let initial_sum = self.marking.iter().sum::<u32>();
            let target_sum = target.iter().sum::<u32>();
            if initial_sum != target_sum {
                return UnreachabilityProof::StateMachineTokenConservation.into();
            }
            // Equal token sum in a live (strongly connected + marked) S-net: any marking
            // with the same sum is reachable (Theorem 5.1.5).
            if self.is_strongly_connected() {
                return ReachabilityProof::LiveStateMachineTokenConservation {
                    marking_sum: initial_sum,
                }.into();
            }
        }

        if self.class().is_marked_graph() && self.is_live() {
            return semi_decision::find_marking_equation_integer_solution(
                &self.dense_net,
                &self.marking,
                &target
            ).map_or_else(
                || UnreachabilityProof::MarkingEquationNoIntegerSolution.into(),
                |solution| {
                    let solution = self.transitions().zip(solution).collect();
                    ReachabilityProof::LiveMarkedGraphMarkingEquationIntegerSolution(solution).into()
                }
            )
        }

        // Live and bounded free-choice systems: the reachability theorem
        // ([Primer, Theorem 5.3.18](crate::literature#theorem-5318--reachability-in-live-bounded-free-choice-systems)).
        //
        // A marking M is reachable from M₀ iff the marking equation
        // `M = M₀ + N·X` has a non-negative integer solution X AND the subnet
        // generated by the *fired* transitions `U = supp(X) = { t | X(t) > 0 }`
        // contains no trap that is unmarked under M. (The reading was verified
        // exhaustively against BFS reachability; see the `fc_*` tests.)
        //
        // Preconditions are established efficiently and soundly:
        // - free-choice: the structural class (exact).
        // - live: `is_live()`, which for a free-choice net is the Commoner/Hack
        //   criterion — necessary and sufficient for liveness, and polynomial.
        // - bounded: structural boundedness (a positive place sub-invariant
        //   `yᵀN ≤ 0`, found by LP). This is a *sound sufficient* condition for
        //   boundedness of `(N, M₀)` — it implies boundedness under every marking
        //   — and holds for every live and bounded free-choice net (which is
        //   covered by S-components, hence carries a positive S-invariant). We
        //   use it rather than `is_bounded()` because the latter currently
        //   depends on the unimplemented `is_covered_by_s_components` and would
        //   spuriously report `false` here.
        //
        // We test the trap condition on the minimum-firing solution returned by
        // the ILP. If the equation is infeasible the target is definitely
        // unreachable. If a solution passes the trap check the target is
        // definitely reachable (witnessed by the Parikh vector). If the trap
        // check fails on this solution we do not conclude unreachability — a
        // different solution might satisfy it — so we abstain rather than guess.
        if self.class() == NetClass::FreeChoice
            && self.is_live()
            && self.dense_net.is_structurally_bounded()
        {
            return semi_decision::find_marking_equation_integer_solution(
                &self.dense_net,
                &self.marking,
                &target,
            ).map_or_else(
                || UnreachabilityProof::MarkingEquationNoIntegerSolution.into(),
                |parikh| {
                    if fired_subnet_has_no_unmarked_trap(&self.dense_net, &parikh, &target) {
                        let witness = self.transitions().zip(parikh.iter().copied()).collect();
                        ReachabilityProof::LiveBoundedFreeChoiceMarkingEquationWithTrapCheck(witness).into()
                    } else {
                        ReachabilityResult::Inconclusive
                    }
                },
            );
        }

        if semi_decision::find_marking_equation_rational_solution(
            &self.dense_net,
            &self.marking,
            &target,
        ).is_none() {
            return UnreachabilityProof::MarkingEquationNoRationalSolution.into();
        }

        // todo: only test ILP if the rational solution is already an integer solution
        if semi_decision::find_marking_equation_integer_solution(
            &self.dense_net,
            &self.marking,
            &target,
        ).is_none() {
            return UnreachabilityProof::MarkingEquationNoIntegerSolution.into();
        }

        let mut explorer = self.explore_coverability(ExplorationOrder::BreadthFirst).core;
        while let Some((_t_idx, node_idx, is_new)) = explorer.explore_next() {
            if !is_new {
                continue;
            }
            let marking = explorer.state_space.marking_at(node_idx);
            if marking.has_omega() {
                return ReachabilityResult::Inconclusive;
            }
            if marking == target {
                let path = explorer.path_from_initial_to(marking)
                    .expect("marking is in graph")
                    .into_iter()
                    .map(|t_idx| self.mapping.transition(t_idx))
                    .collect();
                return ReachabilityProof::FiringSequence(path).into()
            }
        }
        UnreachabilityProof::ExhaustiveSearch.into()
    }
}

#[cfg(test)]
mod tests {
    use crate::builder::NetBuilder;
    use crate::class::NetClass;
    use crate::core::analysis::semi_decision;
    use crate::core::state_space::ExplorationOrder;
    use crate::net::{Net, Place};
    use crate::prelude::Marking;

    /// Esparza's Lecture Notes Figure 5.3: a live, bounded, free-choice net that
    /// is not an S-net or T-net. `•t1 = •t2 = {s1,s2}` (free choice); `t7`
    /// synchronises on `{s7,s8}`. Returns the net and its eight place handles.
    fn esparza_fig_5_3() -> (Net, [Place; 8]) {
        let mut b = NetBuilder::new();
        let [s1, s2, s3, s4, s5, s6, s7, s8] = b.add_places();
        let [t1, t2, t3, t4, t5, t6, t7] = b.add_transitions();
        b.add_arc((s1, t1)); b.add_arc((s2, t1));
        b.add_arc((s1, t2)); b.add_arc((s2, t2));
        b.add_arc((t1, s3)); b.add_arc((t1, s4));
        b.add_arc((t2, s5)); b.add_arc((t2, s6));
        b.add_arc((s3, t3)); b.add_arc((t3, s7));
        b.add_arc((s4, t4)); b.add_arc((t4, s8));
        b.add_arc((s5, t5)); b.add_arc((t5, s7));
        b.add_arc((s6, t6)); b.add_arc((t6, s8));
        b.add_arc((s7, t7)); b.add_arc((s8, t7));
        b.add_arc((t7, s1)); b.add_arc((t7, s2));
        (b.build().unwrap(), [s1, s2, s3, s4, s5, s6, s7, s8])
    }

    /// Enumerate every marking assigning `0..=max` tokens to each place.
    fn enumerate_markings(places: &[Place], max: u32, mut f: impl FnMut(Marking<u32>)) {
        let radix = (max + 1) as usize;
        let total = radix.pow(u32::try_from(places.len()).unwrap());
        for code in 0..total {
            let mut c = code;
            let entries: Vec<(Place, u32)> = places
                .iter()
                .filter_map(|&p| {
                    let v = u32::try_from(c % radix).unwrap();
                    c /= radix;
                    (v > 0).then_some((p, v))
                })
                .collect();
            f(entries.into_iter().collect());
        }
    }

    /// Exhaustively cross-check the free-choice decider against ground-truth BFS
    /// reachability over every marking up to `max` tokens per place. Asserts
    /// SOUNDNESS: any `Reachable` verdict is BFS-reachable, any `Unreachable`
    /// verdict is BFS-unreachable. Returns `(reach, unreach, inconclusive,
    /// feasible_but_unreachable)` for reporting how the trap branch is exercised.
    fn crosscheck_sound(
        net: &Net,
        m0: impl Into<Marking<u32>>,
        places: &[Place],
        max: u32,
    ) -> (u32, u32, u32, u32) {
        let sys = net.with_initial_marking(m0);
        assert_eq!(sys.class(), NetClass::FreeChoice, "test net must be genuinely free-choice");
        assert!(sys.is_live(), "test net must be live");
        assert!(sys.dense_net.is_structurally_bounded(), "test net must be (structurally) bounded");

        // Independent ground truth: drive BFS reachability to completion.
        let mut ex = sys.explore_reachability(ExplorationOrder::BreadthFirst);
        ex.explore_iter().for_each(drop);

        let (mut n_reach, mut n_unreach, mut n_incon, mut feasible_unreachable) = (0, 0, 0, 0);
        enumerate_markings(places, max, |m| {
            let bfs_reachable = ex.contains_marking(m.clone());
            let decoded = sys.mapping.decode(m.clone());
            let feasible = semi_decision::find_marking_equation_integer_solution(
                &sys.dense_net,
                &sys.marking,
                &decoded,
            ).is_some();
            if feasible && !bfs_reachable {
                feasible_unreachable += 1;
            }
            match sys.analyze_reachability(&m) {
                super::ReachabilityResult::Reachable(_) => {
                    n_reach += 1;
                    // SOUNDNESS: a Reachable verdict must be genuinely reachable.
                    assert!(bfs_reachable, "UNSOUND: decider says Reachable but BFS disagrees: {m:?}");
                }
                super::ReachabilityResult::Unreachable(_) => {
                    n_unreach += 1;
                    // SOUNDNESS: an Unreachable verdict must be genuinely unreachable.
                    assert!(!bfs_reachable, "UNSOUND: decider says Unreachable but BFS reached it: {m:?}");
                }
                super::ReachabilityResult::Inconclusive => {
                    n_incon += 1;
                    // We only abstain on feasible-but-unreachable targets here.
                    assert!(!bfs_reachable, "INCOMPLETE: abstained on a reachable target: {m:?}");
                }
            }
        });
        (n_reach, n_unreach, n_incon, feasible_unreachable)
    }

    /// Exhaustive soundness + completeness sweep against BFS ground truth.
    ///
    /// For the live and bounded free-choice net of Figure 5.3, every marking with
    /// at most one token per place is classified by the decider and by an
    /// independent BFS. The decider must never disagree with BFS on a definite
    /// verdict (soundness), must prove every reachable marking `Reachable`
    /// (completeness on this net), and abstains only on feasible-but-unreachable
    /// targets. The net is genuinely discriminating: two markings satisfy the
    /// marking equation yet are unreachable.
    #[test]
    fn fc_reachability_matches_bfs_exhaustively() {
        let (net, s) = esparza_fig_5_3();
        let (reach, _unreach, incon, feasible_but_unreachable) =
            crosscheck_sound(&net, [(s[0], 1), (s[1], 1)], &s, 1);
        assert_eq!(reach, 8, "expected 8 reachable safe markings proved");
        assert_eq!(incon, feasible_but_unreachable, "abstain only on feasible-but-unreachable");
        assert_eq!(feasible_but_unreachable, 2, "Fig 5.3 must exercise the trap condition");
    }

    /// A known-reachable target on a live and bounded free-choice net is proved
    /// reachable with the dedicated trap-check witness (not the exploration
    /// fallback), and the witness Parikh vector realises the marking equation.
    #[test]
    fn fc_reachable_target_has_trap_check_witness() {
        let (net, s) = esparza_fig_5_3();
        let sys = net.with_initial_marking([(s[0], 1), (s[1], 1)]);
        assert_eq!(sys.class(), NetClass::FreeChoice);
        // Fire t1 (s1,s2 -> s3,s4): (s3,s4) is reachable in one step.
        let target: Marking<u32> = [(s[2], 1), (s[3], 1)].into();
        match sys.analyze_reachability(&target) {
            super::ReachabilityResult::Reachable(
                super::ReachabilityProof::LiveBoundedFreeChoiceMarkingEquationWithTrapCheck(parikh),
            ) => {
                // Exactly the transitions with a positive count were "fired".
                let fired: u32 = parikh.values().copied().sum();
                assert!(fired >= 1, "witness must fire at least one transition");
            }
            other => panic!("expected free-choice trap-check witness, got {other:?}"),
        }
        assert!(sys.is_reachable(&target));
        assert_eq!(sys.is_efficiently_reachable(&target), Some(true));
    }

    /// A target whose token content violates the net's place invariants has no
    /// integer marking-equation solution, so it is proved unreachable.
    #[test]
    fn fc_unreachable_marking_equation_infeasible() {
        let (net, s) = esparza_fig_5_3();
        let sys = net.with_initial_marking([(s[0], 1), (s[1], 1)]);
        // s1 alone (odd token content) cannot satisfy the marking equation:
        // every reachable marking of this system carries an even token count.
        let target: Marking<u32> = [(s[0], 1)].into();
        assert!(
            matches!(
                sys.analyze_reachability(&target),
                super::ReachabilityResult::Unreachable(
                    super::UnreachabilityProof::MarkingEquationNoIntegerSolution
                )
            ),
            "expected marking-equation-infeasible unreachability proof"
        );
        assert!(!sys.is_reachable(&target));
        assert_eq!(sys.is_efficiently_reachable(&target), Some(false));
    }

    /// A target that satisfies the marking equation but is genuinely unreachable
    /// (it mixes outputs of the two mutually-exclusive choices) makes the trap
    /// check fail on the minimum-firing solution. The decider abstains
    /// (`Inconclusive`) rather than guess — it never claims reachability.
    #[test]
    fn fc_abstains_on_feasible_but_unreachable() {
        let (net, s) = esparza_fig_5_3();
        let sys = net.with_initial_marking([(s[0], 1), (s[1], 1)]);
        // s3 requires firing t1; s6 requires firing t2. With one token-pair only
        // one of t1/t2 can fire, so (s3,s6) is unreachable — yet the marking
        // equation (a relaxation) admits an integer solution.
        let target: Marking<u32> = [(s[2], 1), (s[5], 1)].into();

        // Precondition: the marking equation is satisfiable (else this would be
        // the trivial infeasible case, not an abstention).
        let decoded = sys.mapping.decode(target.clone());
        assert!(
            semi_decision::find_marking_equation_integer_solution(
                &sys.dense_net, &sys.marking, &decoded,
            ).is_some(),
            "target must satisfy the marking equation for this to test the trap branch"
        );

        // Ground truth: genuinely unreachable.
        let mut ex = sys.explore_reachability(ExplorationOrder::BreadthFirst);
        ex.explore_iter().for_each(drop);
        assert!(!ex.contains_marking(target.clone()), "target must be unreachable");

        // The decider abstains rather than emitting a (false) Reachable.
        assert!(
            matches!(sys.analyze_reachability(&target), super::ReachabilityResult::Inconclusive),
            "decider must abstain on a feasible-but-unreachable free-choice target"
        );
        assert!(!sys.is_reachable(&target));
        assert_eq!(sys.is_efficiently_reachable(&target), None);
    }

    #[test]
    fn s_net_reachability_dispatches() {
        let (net, p0, _t0, p1, _t1) = crate::api::system::tests::two_place_cycle();
        let sys = net.with_initial_marking([(p0, 1)]);
        assert!(sys.is_reachable(&[(p1, 1)].into()));
        assert!(sys.is_reachable(&[(p0, 1)].into()));
        assert!(!sys.is_reachable(&[(p0, 2)].into()));
        assert!(!sys.is_reachable(&[].into()));
    }

    #[test]
    fn t_net_reachability_dispatches() {
        let mut b = NetBuilder::new();
        let [p0, p1, p2] = b.add_places();
        let [t0, t1] = b.add_transitions();
        b.add_arc((p0, t0));
        b.add_arc((p1, t0));
        b.add_arcs((t0, p2, t1));
        b.add_arc((t1, p0));
        b.add_arc((t1, p1));
        let net = b.build().unwrap();
        assert_eq!(net.class(), NetClass::MarkedGraph);
        let sys = net.with_initial_marking([(p0, 1), (p1, 1)]);
        assert!(sys.is_reachable(&[(p2, 1)].into()));
        assert!(sys.is_reachable(&[(p0, 1), (p1, 1)].into()));
        assert!(!sys.is_reachable(&[(p1, 1)].into()));
    }

    #[test]
    fn general_net_reachability_fallback() {
        let mut b = NetBuilder::new();
        let [p0, p1, p2] = b.add_places();
        let [t0, t1, t2] = b.add_transitions();
        b.add_arcs((p0, t0, p1));
        b.add_arcs((p0, t1, p2));
        b.add_arcs((p1, t2, p0));
        b.add_arcs((p2, t2, p0));
        let net = b.build().unwrap();
        assert_eq!(net.class(), NetClass::General);
        let sys = net.with_initial_marking([(p0, 1)]);
        assert!(sys.is_reachable(&[(p0, 1)].into()));
        assert!(sys.is_reachable(&[(p1, 1)].into()));
    }
}