#let meta = (
  title: "High Performance Petri Net Model Checker",
  german-title: "Hochleistungs-Petri-Netz-Modellprüfer",
  author: "Michael Dyer",
  chair: "Chair of Information Systems and Business Process Management (i17)",
  school: "TUM School of Computation, Information and Technology",
  department: "Department of Informatics",
  university: "Technical University of Munich",
  degree: "Master of Science",
  examiner: "Prof. Dr. Stefanie Rinderle-Ma",
  supervisor: "Dr. Jürgen Mangler",
  supervisor-2: none,
  matriculation-number: none,
  hood: "Garching",
  submission-date: "02.11.2026",
)
